from __future__ import annotations

import json
from pathlib import Path
from typing import Any
from urllib.parse import urljoin

import pytest

from w3lib.url import safe_url_string

_KNOWN_FAILURES: set[tuple[str | None, str]] = {
    ("http://example.org/foo/bar", "http://example\t.\norg"),
    (None, "https://test:@test"),
    (None, "https://:@test"),
    (None, "non-special://test:@test/x"),
    (None, "non-special://:@test/x"),
    ("http://example.org/foo/bar", "http://f:00000000000000000000080/c"),
    ("http://example.org/foo/bar", "\\x"),
    ("http://example.org/foo/bar", "\\\\x\\hello"),
    (None, "http://é@é"),
    (None, "http://é@example.com"),
    ("http://example.org/foo/bar", "http://&a:foo(b]c@d:2/"),
    ("http://example.org/foo/bar", "http://::@c@d:2"),
    ("http://example.org/foo/bar", "http:\\\\foo.com\\"),
    ("http://example.org/foo/bar", "http:\\\\a\\b:c\\d@foo.com\\"),
    ("http://example.org/foo/bar", "http://[2001::1]"),
    ("http://example.org/foo/bar", "http://[::127.0.0.1]"),
    ("http://example.org/foo/bar", "http://[0:0:0:0:0:0:13.1.68.3]"),
    ("http://example.org/foo/bar", "http://[2001::1]:80"),
    ("http://example.org/foo/bar", "ftp:/example.com/"),
    ("http://example.org/foo/bar", "https:/example.com/"),
    (None, "file://example:1/"),
    (None, "file://example%/"),
    ("http://example.org/foo/bar", "ws:/example.com/"),
    ("http://example.org/foo/bar", "wss:/example.com/"),
    ("http://example.org/foo/bar", "ftp:example.com/"),
    ("http://example.org/foo/bar", "https:example.com/"),
    ("http://example.org/foo/bar", "ws:example.com/"),
    ("http://example.org/foo/bar", "wss:example.com/"),
    ("file:///tmp/mock/path", "file:c:\\foo\\bar.html"),
    ("file:///tmp/mock/path", "  File:c|////foo\\bar.html"),
    ("file:///tmp/mock/path", "C|/foo/bar"),
    ("file:///tmp/mock/path", "/C|\\foo\\bar"),
    ("file:///tmp/mock/path", "//C|/foo/bar"),
    ("file:///tmp/mock/path", "\\\\server\\file"),
    ("file:///tmp/mock/path", "/\\server/file"),
    ("file:///tmp/mock/path", "//"),
    ("file:///tmp/mock/path", "file://test"),
    ("file:///tmp/mock/path", "file://localhost"),
    ("file:///tmp/mock/path", "file://localhost/"),
    ("file:///tmp/mock/path", "file://localhost/test"),
    (None, "file:///w|/m"),
    (None, "file:C|/m/"),
    (None, "file:C||/m/"),
    (None, "http://example.com/././foo"),
    (None, "http://example.com/./.foo"),
    (None, "http://example.com/foo/."),
    (None, "http://example.com/foo/./"),
    (None, "http://example.com/foo/bar/.."),
    (None, "http://example.com/foo/bar/../"),
    (None, "http://example.com/foo/bar/../ton"),
    (None, "http://example.com/foo/bar/../ton/../../a"),
    (None, "http://example.com/foo/../../.."),
    (None, "http://example.com/foo/../../../ton"),
    (None, "http://example.com/foo/%2e"),
    (None, "http://example.com/foo/%2e./%2e%2e/.%2e/%2e.bar"),
    (None, "http://example.com////../.."),
    (None, "http://example.com/foo/bar//../.."),
    (None, "http://example.com/foo/bar//.."),
    (None, "http://www.google.com"),
    (None, "http://192.0x00A80001"),
    (None, "http://www/foo/%2E/html"),
    (None, "http://user:pass@/"),
    (None, "http://foo:80/"),
    (None, "https://foo:443/"),
    (None, "ftp://foo:21/"),
    (None, "ws://foo:80/"),
    (None, "wss://foo:443/"),
    (None, "http:/example.com/"),
    (None, "ftp:/example.com/"),
    (None, "https:/example.com/"),
    (None, "ws:/example.com/"),
    (None, "wss:/example.com/"),
    (None, "http:example.com/"),
    (None, "ftp:example.com/"),
    (None, "https:example.com/"),
    (None, "ws:example.com/"),
    (None, "wss:example.com/"),
    (None, "https://example.com/aaa/bbb/%2e%2e?query"),
    (None, "http:@www.example.com"),
    (None, "http:/@www.example.com"),
    (None, "http://@www.example.com"),
    (None, "http:a:b@www.example.com"),
    (None, "http:/a:b@www.example.com"),
    (None, "http://a:b@www.example.com"),
    (None, "http://@pple.com"),
    (None, "http::b@www.example.com"),
    (None, "http:/:b@www.example.com"),
    (None, "http://:b@www.example.com"),
    (None, "http:/:@/www.example.com"),
    (None, "http://user@/www.example.com"),
    (None, "http:@/www.example.com"),
    (None, "http:/@/www.example.com"),
    (None, "http://@/www.example.com"),
    (None, "https:@/www.example.com"),
    (None, "http:a:b@/www.example.com"),
    (None, "http:/a:b@/www.example.com"),
    (None, "http://a:b@/www.example.com"),
    (None, "http::@/www.example.com"),
    (None, "http:a:@www.example.com"),
    (None, "http:/a:@www.example.com"),
    (None, "http://a:@www.example.com"),
    (None, "http://www.@pple.com"),
    (None, "http:@:www.example.com"),
    (None, "http:/@:www.example.com"),
    (None, "http://:@www.example.com"),
    ("http://www.example.com/test", "http://www.example2.com"),
    ("http://www.example.com/test", "//www.example2.com"),
    ("http://www.example.com/test", "file:..."),
    ("http://www.example.com/test", "file:.."),
    ("http://www.example.com/test", "file:a"),
    (None, "file:."),
    ("http://www.example.com/test", "file:."),
    ("http://other.com/", "http://ExAmPlE.CoM"),
    ("http://other.com/", "http://example example.com"),
    ("http://other.com/", "http://Goo%20 goo%7C|.com"),
    ("http://other.com/", "http://GOO\xa0\u3000goo.com"),
    ("http://other.com/", "http://GOO\u200b\u2060\ufeffgoo.com"),
    ("http://other.com/", "http://www.foo。bar.com"),
    ("http://other.com/", "http://\ufdd0zyx.com"),
    ("http://other.com/", "http://%ef%b7%90zyx.com"),
    (None, "https://�"),
    (None, "https://%EF%BF%BD"),
    (None, "http://a.b.c.xn--pokxncvks"),
    (None, "http://10.0.0.xn--pokxncvks"),
    (None, "http://a.b.c.XN--pokxncvks"),
    (None, "http://a.b.c.Xn--pokxncvks"),
    (None, "http://10.0.0.XN--pokxncvks"),
    (None, "http://10.0.0.xN--pokxncvks"),
    ("http://other.com/", "http://Ｇｏ.com"),
    ("http://other.com/", "http://％４１.com"),
    ("http://other.com/", "http://%ef%bc%85%ef%bc%94%ef%bc%91.com"),
    ("http://other.com/", "http://％００.com"),
    ("http://other.com/", "http://%ef%bc%85%ef%bc%90%ef%bc%90.com"),
    ("http://other.com/", "http://你好你好"),
    (None, "https://faß.ExAmPlE/"),
    (None, "sc://faß.ExAmPlE/"),
    ("http://other.com/", "http://%zz%66%a.com"),
    ("http://other.com/", "http://%25"),
    ("http://other.com/", "http://hello%00"),
    ("http://other.com/", "http://%30%78%63%30%2e%30%32%35%30.01"),
    ("http://other.com/", "http://%30%78%63%30%2e%30%32%35%30.01%2e"),
    ("http://other.com/", "http://192.168.0.257"),
    ("http://other.com/", "http://%3g%78%63%30%2e%30%32%35%30%2E.01"),
    ("http://other.com/", "http://192.168.0.1 hello"),
    (None, "https://x x:12"),
    ("http://other.com/", "http://０Ｘｃ０．０２５０．０１"),
    ("http://other.com/", "http://[::%31]"),
    (None, "https://localhost#🔥"),
    ("test:test", "#"),
    ("mailto:x@x.com", "#x"),
    ("data:,", "#x"),
    ("about:blank", "#x"),
    ("about:blank", "#x:y"),
    ("test:test?test", "#"),
    ("http://doesnotmatter/", "https://@@@example"),
    ("sc:sd", "i"),
    ("sc:sd/sd", "i"),
    ("sc:/pa/pa", "i"),
    ("sc://ho/pa", "i"),
    ("sc:///pa/pa", "i"),
    ("sc:sd", "../i"),
    ("sc:sd/sd", "../i"),
    ("sc:/pa/pa", "../i"),
    ("sc://ho/pa", "../i"),
    ("sc:///pa/pa", "../i"),
    ("sc:sd", "/i"),
    ("sc:sd/sd", "/i"),
    ("sc:/pa/pa", "/i"),
    ("sc://ho/pa", "/i"),
    ("sc:///pa/pa", "/i"),
    ("sc:sd", "?i"),
    ("sc:sd/sd", "?i"),
    ("sc:/pa/pa", "?i"),
    ("sc://ho/pa", "?i"),
    ("sc:///pa/pa", "?i"),
    ("sc:sd", "#i"),
    ("sc:sd/sd", "#i"),
    ("sc:/pa/pa", "#i"),
    ("sc://ho/pa", "#i"),
    ("sc:///pa/pa", "#i"),
    (None, "about:/../"),
    (None, "data:/../"),
    (None, "javascript:/../"),
    (None, "mailto:/../"),
    (None, "sc://ñ.test/"),
    (None, "sc://@/"),
    (None, "sc://te@s:t@/"),
    (None, "sc://:/"),
    (None, "sc://:12/"),
    ("sc://ñ", "x"),
    (None, "sc://a\x00b/"),
    (None, "sc://a b/"),
    (None, "sc://a<b"),
    (None, "sc://a>b"),
    (None, "sc://a\\b/"),
    (None, "sc://a^b"),
    (None, "sc://a|b/"),
    (None, "http://a\x00b/"),
    (None, "http://a\x01b/"),
    (None, "http://a\x02b/"),
    (None, "http://a\x03b/"),
    (None, "http://a\x04b/"),
    (None, "http://a\x05b/"),
    (None, "http://a\x06b/"),
    (None, "http://a\x07b/"),
    (None, "http://a\x08b/"),
    (None, "http://a\x0bb/"),
    (None, "http://a\x0cb/"),
    (None, "http://a\x0eb/"),
    (None, "http://a\x0fb/"),
    (None, "http://a\x10b/"),
    (None, "http://a\x11b/"),
    (None, "http://a\x12b/"),
    (None, "http://a\x13b/"),
    (None, "http://a\x14b/"),
    (None, "http://a\x15b/"),
    (None, "http://a\x16b/"),
    (None, "http://a\x17b/"),
    (None, "http://a\x18b/"),
    (None, "http://a\x19b/"),
    (None, "http://a\x1ab/"),
    (None, "http://a\x1bb/"),
    (None, "http://a\x1cb/"),
    (None, "http://a\x1db/"),
    (None, "http://a\x1eb/"),
    (None, "http://a\x1fb/"),
    (None, "http://a b/"),
    (None, "http://a%b/"),
    (None, "http://a<b"),
    (None, "http://a>b"),
    (None, "http://a^b"),
    (None, "http://a|b/"),
    (None, "http://a\x7fb/"),
    (None, "http://ho%00st/"),
    (None, "http://ho%01st/"),
    (None, "http://ho%02st/"),
    (None, "http://ho%03st/"),
    (None, "http://ho%04st/"),
    (None, "http://ho%05st/"),
    (None, "http://ho%06st/"),
    (None, "http://ho%07st/"),
    (None, "http://ho%08st/"),
    (None, "http://ho%09st/"),
    (None, "http://ho%0Ast/"),
    (None, "http://ho%0Bst/"),
    (None, "http://ho%0Cst/"),
    (None, "http://ho%0Dst/"),
    (None, "http://ho%0Est/"),
    (None, "http://ho%0Fst/"),
    (None, "http://ho%10st/"),
    (None, "http://ho%11st/"),
    (None, "http://ho%12st/"),
    (None, "http://ho%13st/"),
    (None, "http://ho%14st/"),
    (None, "http://ho%15st/"),
    (None, "http://ho%16st/"),
    (None, "http://ho%17st/"),
    (None, "http://ho%18st/"),
    (None, "http://ho%19st/"),
    (None, "http://ho%1Ast/"),
    (None, "http://ho%1Bst/"),
    (None, "http://ho%1Cst/"),
    (None, "http://ho%1Dst/"),
    (None, "http://ho%1Est/"),
    (None, "http://ho%1Fst/"),
    (None, "http://ho%20st/"),
    (None, "http://ho%23st/"),
    (None, "http://ho%25st/"),
    (None, "http://ho%2Fst/"),
    (None, "http://ho%3Ast/"),
    (None, "http://ho%3Cst/"),
    (None, "http://ho%3Est/"),
    (None, "http://ho%3Fst/"),
    (None, "http://ho%40st/"),
    (None, "http://ho%5Bst/"),
    (None, "http://ho%5Cst/"),
    (None, "http://ho%5Dst/"),
    (None, "http://ho%7Cst/"),
    (None, "http://ho%7Fst/"),
    (
        None,
        "sc://\x01\x02\x03\x04\x05\x06\x07\x08\x0b\x0c\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f\x7f!\"$%&'()*+,-.;=_`{}~/",
    ),
    (None, "ftp://example.com%80/"),
    (None, "ftp://example.com%A0/"),
    (None, "https://example.com%80/"),
    (None, "https://example.com%A0/"),
    (None, "ftp://%e2%98%83"),
    (None, "https://%e2%98%83"),
    ("https://example.org/foo/bar", "http:"),
    ("http://other.com/", "http://1.2.3.4./"),
    ("http://other.com/", "http://192.168.257"),
    ("http://other.com/", "http://192.168.257."),
    ("http://other.com/", "http://192.168.257.com"),
    ("http://other.com/", "http://256"),
    ("http://other.com/", "http://256.com"),
    ("http://other.com/", "http://999999999"),
    ("http://other.com/", "http://999999999."),
    ("http://other.com/", "http://999999999.com"),
    ("http://other.com/", "http://10000000000"),
    ("http://other.com/", "http://10000000000.com"),
    ("http://other.com/", "http://4294967295"),
    ("http://other.com/", "http://4294967296"),
    ("http://other.com/", "http://18446744073709551616"),
    ("http://other.com/", "http://18446744075840258049"),
    ("http://other.com/", "http://0xffffffff"),
    ("http://other.com/", "http://0xffffffff1"),
    ("http://other.com/", "http://256.256.256.256"),
    (None, "https://0x.0x.0"),
    (None, "https://0x.0x.0x.0x"),
    (None, "https://00.00.00.00"),
    (None, "https://0000000000000000000000000000000000000000177.0.0.1"),
    (None, "https://0x100000000/test"),
    (None, "https://256.0.0.1/test"),
    (None, "file://%43%3A"),
    (None, "file://%43%7C"),
    (None, "file://%43|"),
    (None, "file://C%7C"),
    (None, "file://%43%7C/"),
    (None, "https://%43%7C/"),
    (None, "asdf://%43|/"),
    ("file:///C:/", ".."),
    ("file:///C:/a/b", "/"),
    ("file://h/C:/a/b", "/"),
    ("file:///C:/a/b", "//d:"),
    ("file:///C:/a/b", "//d:/.."),
    ("file:///test?test#test", ""),
    (None, "file:\\\\localhost//"),
    (None, "file://localhost//a//../..//"),
    ("file:///elephant", "/////mouse"),
    ("file://lion/", "\\//pig"),
    ("file://lion/", "\\/localhost//pig"),
    ("file://lion/", "//localhost//pig"),
    ("file://lion/", "/..//localhost//pig"),
    ("file://ape/", "file://"),
    ("file://host/dir/file", "C|"),
    ("file://host/D:/dir1/dir2/file", "C|"),
    ("file://host/dir/file", "C|#"),
    ("file://host/dir/file", "C|?"),
    ("file://host/dir/file", "C|/"),
    ("file://host/dir/file", "C|\n/"),
    ("file://host/dir/file", "C|\\"),
    ("file:///c:/baz/qux", "/c|/foo/bar"),
    ("file:///c:/baz/qux", "file:\\c:\\foo\\bar"),
    ("abc://x/y/z/C:/", ".."),
    ("file://x/C:/", ".."),
    ("file://host/", "C|/"),
    ("file://host/", "//C:/"),
    ("file://host/", "file://C:/"),
    ("file://host/", "///C:/"),
    ("file://host/", "file:///C:/"),
    (None, "file:/C|/"),
    (None, "file://C|/"),
    (None, "file:"),
    (None, "file:#frag"),
    (None, "file:///./Y"),
    (None, "file:///./Y:"),
    (None, "\\\\\\.\\Y:"),
    (None, "file:///./y"),
    (None, "file:///./y:"),
    (None, "\\\\\\.\\y:"),
    (None, "file://localhost//a//../..//foo"),
    (None, "file://localhost////foo"),
    ("file:///", "file:////one/two"),
    ("file:///", "////one/two"),
    ("file:////", "file:///.//"),
    (None, "file:.//p"),
    (None, "file:/.//p"),
    ("http://example.net/", "http://[1:0::]"),
    (None, "http://?"),
    (None, "http://#"),
    (None, "sc://ñ"),
    (None, "sc://ñ?x"),
    (None, "sc://ñ#x"),
    ("sc://ñ", "#x"),
    ("sc://ñ", "?x"),
    ("sc://x/", "///"),
    ("sc://x/", "////"),
    ("sc://x/", "////x/"),
    (None, "non-spec:/..//"),
    (None, "non-spec:/a/..//"),
    (None, "non-spec:/..//path"),
    (None, "non-spec:/a/..//path"),
    ("non-spec:/p", "/.//path"),
    ("non-spec:/p", "/..//path"),
    ("non-spec:/p", "..//path"),
    ("non-spec:/p", "a/..//path"),
    ("non-spec:/..//p", ""),
    ("non-spec:/..//p", "path"),
    ("non-spec:/.//p", "../path"),
    (None, "non-special://[1:2:0:0:5:0:0:0]/"),
    (None, "non-special://[1:2:0:0:0:0:0:3]/"),
    (None, "http://0x7f.0.0.0x7g"),
    (None, "http://0X7F.0.0.0X7G"),
    (None, "http://[0:1:0:1:0:1:0:1]"),
    (None, "http://[1:0:1:0:1:0:1:0]"),
    (None, "a"),
    (None, "a/"),
    (None, "a//"),
    ("a:", "test-a-colon.html"),
    ("a:b", "test-a-colon-b.html"),
    ("a:/", "test-a-colon-slash.html"),
    ("a://", "test-a-colon-slash-slash.html"),
    ("a:/b", "test-a-colon-slash-b.html"),
    ("a://b", "test-a-colon-slash-slash-b.html"),
    (None, "file://a%C2%ADb/p"),
    (None, "file://loC𝐀𝐋𝐇𝐨𝐬𝐭/usr/bin"),
    (None, "file://\xad/p"),
    (None, "file://%C2%AD/p"),
    ("http://example.org", "https://user:pass[\x7f@foo/bar"),
    (None, "foo:// !\"$%&'()*+,-.;<=>@[\\]^_`{|}~@host/"),
    (None, "wss:// !\"$%&'()*+,-.;<=>@[]^_`{|}~@host/"),
    (None, "foo://joe: !\"$%&'()*+,-.:;<=>@[\\]^_`{|}~@host/"),
    (None, "wss://joe: !\"$%&'()*+,-.:;<=>@[]^_`{|}~@host/"),
    (None, "#"),
    (None, "?"),
    ("http://other.com/", "http://1.2.3.4.5"),
    ("http://other.com/", "http://1.2.3.4.5."),
    (None, "http://0..0x300/"),
    (None, "http://0..0x300./"),
    ("http://other.com/", "http://256.256.256.256.256"),
    ("http://other.com/", "http://256.256.256.256.256."),
    (None, "http://1.2.3.08"),
    (None, "http://1.2.3.08."),
    (None, "http://1.2.3.09"),
    (None, "http://09.2.3.4"),
    (None, "http://09.2.3.4."),
    (None, "http://01.2.3.4.5"),
    (None, "http://01.2.3.4.5."),
    (None, "http://0x100.2.3.4"),
    (None, "http://0x100.2.3.4."),
    (None, "http://0x1.2.3.4.5"),
    (None, "http://0x1.2.3.4.5."),
    (None, "http://foo.1.2.3.4"),
    (None, "http://foo.1.2.3.4."),
    (None, "http://foo.2.3.4"),
    (None, "http://foo.2.3.4."),
    (None, "http://foo.09"),
    (None, "http://foo.09."),
    (None, "http://foo.0x4"),
    (None, "http://foo.0x4."),
    (None, "http://foo.09.."),
    (None, "http://0999999999999999999/"),
    (None, "http://foo.0x"),
    (None, "http://foo.0XFfFfFfFfFfFfFfFfFfAcE123"),
    (None, "http://💩.123/"),
    (None, "https://\x00y"),
    (None, "https://\uffffy"),
    (None, ""),
    (None, "https://a%C2%ADb/"),
    (None, "https://\xad/"),
    (None, "https://%C2%AD/"),
    (None, "data://test/a/../b"),
    (None, "data://:443"),
    (None, "javascript://test/a/../b"),
    (None, "javascript://:443"),
    (None, "mailto://test/a/../b"),
    (None, "mailto://:443"),
    (None, "intent://test/a/../b"),
    (None, "intent://:443"),
    (None, "urn://test/a/../b"),
    (None, "urn://:443"),
    (None, "turn://test/a/../b"),
    (None, "turn://:443"),
    (None, "stun://test/a/../b"),
    (None, "stun://:443"),
    ("http://example.org/", "///test"),
    ("http://example.org/", "///\\//\\//test"),
    ("http://example.org/", "///example.org/path"),
    ("http://example.org/", "/\\/\\//example.org/../path"),
    ("file:///", "/\\//\\/a/../"),
    ("file:///", "//a/../"),
    (None, "non-special://host\\a"),
    ("foo://foo/a", "\\a"),
    ("foo://foo/a", "\\/a"),
    ("foo://foo/a", "\\\\a"),
}

_DIVERGENCES: dict[tuple[str | None, str], str] = {}


def _params() -> list[Any]:
    path = Path(__file__).parent / "wpt" / "urltestdata.json"
    params = []
    for case in json.loads(path.read_text(encoding="utf-8")):
        if isinstance(case, str):
            continue
        key = (case["base"], case["input"])
        marks = []
        if key in _KNOWN_FAILURES:
            marks.append(pytest.mark.xfail(strict=True))
        elif key in _DIVERGENCES:
            marks.append(pytest.mark.xfail(strict=True, reason=_DIVERGENCES[key]))
        params.append(pytest.param(case, id=repr(key), marks=marks))
    return params


def _parse(base: str | None, url: str) -> str:
    if base is not None:
        url = urljoin(base, url)
    return safe_url_string(url)


@pytest.mark.parametrize("case", _params())
def test_urltestdata(case: dict[str, Any]) -> None:
    if case.get("failure"):
        with pytest.raises(ValueError):  # noqa: PT011
            _parse(case["base"], case["input"])
    else:
        assert _parse(case["base"], case["input"]) == safe_url_string(case["href"])
