from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from w3lib.url import safe_url_string

_KNOWN_FAILURES: set[tuple[str | None, str]] = {
    (None, "file://example:1/"),
    (None, "file://example%/"),
    (None, "file:C|/m/"),
    (None, "file:C||/m/"),
    (None, "http://user:pass@/"),
    (None, "http:/example.com/"),
    (None, "ftp:/example.com/"),
    (None, "https:/example.com/"),
    (None, "ws:/example.com/"),
    (None, "wss:/example.com/"),
    (None, "http:example.com/"),
    (None, "ftp:example.com/"),
    (None, "https:example.com/"),
    (None, "ws:example.com/"),
    (None, "wss:example.com/"),
    (None, "http:@www.example.com"),
    (None, "http:/@www.example.com"),
    (None, "http:a:b@www.example.com"),
    (None, "http:/a:b@www.example.com"),
    (None, "http::b@www.example.com"),
    (None, "http:/:b@www.example.com"),
    (None, "http:/:@/www.example.com"),
    (None, "http://user@/www.example.com"),
    (None, "http:@/www.example.com"),
    (None, "http:/@/www.example.com"),
    (None, "http://@/www.example.com"),
    (None, "https:@/www.example.com"),
    (None, "http:a:b@/www.example.com"),
    (None, "http:/a:b@/www.example.com"),
    (None, "http://a:b@/www.example.com"),
    (None, "http::@/www.example.com"),
    (None, "http:a:@www.example.com"),
    (None, "http:/a:@www.example.com"),
    (None, "http:@:www.example.com"),
    (None, "http:/@:www.example.com"),
    (None, "file:."),
    (None, "https://�"),
    (None, "https://%EF%BF%BD"),
    (None, "https://x x:12"),
    (None, "about:/../"),
    (None, "data:/../"),
    (None, "javascript:/../"),
    (None, "mailto:/../"),
    (None, "sc://@/"),
    (None, "sc://te@s:t@/"),
    (None, "sc://:/"),
    (None, "sc://:12/"),
    (None, "sc://a\x00b/"),
    (None, "sc://a b/"),
    (None, "sc://a<b"),
    (None, "sc://a>b"),
    (None, "sc://a\\b/"),
    (None, "sc://a^b"),
    (None, "sc://a|b/"),
    (None, "http://a\x00b/"),
    (None, "http://a\x01b/"),
    (None, "http://a\x02b/"),
    (None, "http://a\x03b/"),
    (None, "http://a\x04b/"),
    (None, "http://a\x05b/"),
    (None, "http://a\x06b/"),
    (None, "http://a\x07b/"),
    (None, "http://a\x08b/"),
    (None, "http://a\x0bb/"),
    (None, "http://a\x0cb/"),
    (None, "http://a\x0eb/"),
    (None, "http://a\x0fb/"),
    (None, "http://a\x10b/"),
    (None, "http://a\x11b/"),
    (None, "http://a\x12b/"),
    (None, "http://a\x13b/"),
    (None, "http://a\x14b/"),
    (None, "http://a\x15b/"),
    (None, "http://a\x16b/"),
    (None, "http://a\x17b/"),
    (None, "http://a\x18b/"),
    (None, "http://a\x19b/"),
    (None, "http://a\x1ab/"),
    (None, "http://a\x1bb/"),
    (None, "http://a\x1cb/"),
    (None, "http://a\x1db/"),
    (None, "http://a\x1eb/"),
    (None, "http://a\x1fb/"),
    (None, "http://a b/"),
    (None, "http://a%b/"),
    (None, "http://a<b"),
    (None, "http://a>b"),
    (None, "http://a^b"),
    (None, "http://a|b/"),
    (None, "http://a\x7fb/"),
    (None, "http://ho%00st/"),
    (None, "http://ho%01st/"),
    (None, "http://ho%02st/"),
    (None, "http://ho%03st/"),
    (None, "http://ho%04st/"),
    (None, "http://ho%05st/"),
    (None, "http://ho%06st/"),
    (None, "http://ho%07st/"),
    (None, "http://ho%08st/"),
    (None, "http://ho%09st/"),
    (None, "http://ho%0Ast/"),
    (None, "http://ho%0Bst/"),
    (None, "http://ho%0Cst/"),
    (None, "http://ho%0Dst/"),
    (None, "http://ho%0Est/"),
    (None, "http://ho%0Fst/"),
    (None, "http://ho%10st/"),
    (None, "http://ho%11st/"),
    (None, "http://ho%12st/"),
    (None, "http://ho%13st/"),
    (None, "http://ho%14st/"),
    (None, "http://ho%15st/"),
    (None, "http://ho%16st/"),
    (None, "http://ho%17st/"),
    (None, "http://ho%18st/"),
    (None, "http://ho%19st/"),
    (None, "http://ho%1Ast/"),
    (None, "http://ho%1Bst/"),
    (None, "http://ho%1Cst/"),
    (None, "http://ho%1Dst/"),
    (None, "http://ho%1Est/"),
    (None, "http://ho%1Fst/"),
    (None, "http://ho%20st/"),
    (None, "http://ho%23st/"),
    (None, "http://ho%25st/"),
    (None, "http://ho%2Fst/"),
    (None, "http://ho%3Ast/"),
    (None, "http://ho%3Cst/"),
    (None, "http://ho%3Est/"),
    (None, "http://ho%3Fst/"),
    (None, "http://ho%40st/"),
    (None, "http://ho%5Bst/"),
    (None, "http://ho%5Cst/"),
    (None, "http://ho%5Dst/"),
    (None, "http://ho%7Cst/"),
    (None, "http://ho%7Fst/"),
    (None, "ftp://example.com%80/"),
    (None, "ftp://example.com%A0/"),
    (None, "https://example.com%80/"),
    (None, "https://example.com%A0/"),
    (None, "https://0x100000000/test"),
    (None, "https://256.0.0.1/test"),
    (None, "file://%43%3A"),
    (None, "file://%43%7C"),
    (None, "file://%43|"),
    (None, "file://C%7C"),
    (None, "file://%43%7C/"),
    (None, "https://%43%7C/"),
    (None, "asdf://%43|/"),
    (None, "file:\\\\localhost//"),
    (None, "file:/C|/"),
    (None, "\\\\\\.\\Y:"),
    (None, "\\\\\\.\\y:"),
    (None, "file:.//p"),
    (None, "file:/.//p"),
    (None, "http://?"),
    (None, "http://#"),
    (None, "non-spec:/..//"),
    (None, "non-spec:/a/..//"),
    (None, "non-spec:/..//path"),
    (None, "non-spec:/a/..//path"),
    (None, "a"),
    (None, "a/"),
    (None, "a//"),
    (None, "file://\xad/p"),
    (None, "file://%C2%AD/p"),
    (None, "#"),
    (None, "?"),
    (None, "http://0..0x300/"),
    (None, "http://0..0x300./"),
    (None, "http://1.2.3.08"),
    (None, "http://1.2.3.08."),
    (None, "http://1.2.3.09"),
    (None, "http://09.2.3.4"),
    (None, "http://09.2.3.4."),
    (None, "http://01.2.3.4.5"),
    (None, "http://01.2.3.4.5."),
    (None, "http://0x100.2.3.4"),
    (None, "http://0x100.2.3.4."),
    (None, "http://0x1.2.3.4.5"),
    (None, "http://0x1.2.3.4.5."),
    (None, "http://foo.1.2.3.4"),
    (None, "http://foo.1.2.3.4."),
    (None, "http://foo.2.3.4"),
    (None, "http://foo.2.3.4."),
    (None, "http://foo.09"),
    (None, "http://foo.09."),
    (None, "http://foo.0x4"),
    (None, "http://foo.0x4."),
    (None, "http://0999999999999999999/"),
    (None, "http://foo.0x"),
    (None, "http://foo.0XFfFfFfFfFfFfFfFfFfAcE123"),
    (None, "http://💩.123/"),
    (None, "https://\x00y"),
    (None, "https://\uffffy"),
    (None, ""),
    (None, "https://\xad/"),
    (None, "https://%C2%AD/"),
    (None, "data://:443"),
    (None, "javascript://:443"),
    (None, "mailto://:443"),
    (None, "intent://:443"),
    (None, "urn://:443"),
    (None, "turn://:443"),
    (None, "stun://:443"),
    (None, "non-special://host\\a"),
}


_DIVERGENCES: dict[tuple[str | None, str], str] = {}


def _params() -> list[Any]:
    path = Path(__file__).parent / "wpt" / "urltestdata.json"
    params = []
    for case in json.loads(path.read_text(encoding="utf-8")):
        if isinstance(case, str):
            continue
        key = (case["base"], case["input"])
        marks = []
        if case["base"] is not None:
            marks.append(pytest.mark.skip(reason="w3lib has no URL join function yet"))
        elif key in _KNOWN_FAILURES:
            marks.append(pytest.mark.xfail(strict=True))
        elif key in _DIVERGENCES:
            marks.append(pytest.mark.xfail(strict=True, reason=_DIVERGENCES[key]))
        params.append(pytest.param(case, id=repr(key), marks=marks))
    return params


@pytest.mark.parametrize("case", _params())
def test_urltestdata(case: dict[str, Any]) -> None:
    if case.get("failure"):
        with pytest.raises(ValueError):  # noqa: PT011
            safe_url_string(case["input"])
    else:
        assert safe_url_string(case["input"]) == safe_url_string(case["href"])
