from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from w3lib.url import _urljoin, safe_url_string

_KNOWN_FAILURES: set[tuple[str | None, str]] = {
    (None, "https://test:@test"),
    (None, "https://:@test"),
    (None, "non-special://test:@test/x"),
    (None, "non-special://:@test/x"),
    (None, "file://example:1/"),
    (None, "file://example%/"),
    (None, "file:///w|/m"),
    (None, "file:C|/m/"),
    (None, "file:C||/m/"),
    (None, "http://192.0x00A80001"),
    (None, "http://user:pass@/"),
    (None, "http://foo:80/"),
    (None, "https://foo:443/"),
    (None, "ftp://foo:21/"),
    (None, "ws://foo:80/"),
    (None, "wss://foo:443/"),
    (None, "http:/example.com/"),
    (None, "ftp:/example.com/"),
    (None, "https:/example.com/"),
    (None, "ws:/example.com/"),
    (None, "wss:/example.com/"),
    (None, "http:example.com/"),
    (None, "ftp:example.com/"),
    (None, "https:example.com/"),
    (None, "ws:example.com/"),
    (None, "wss:example.com/"),
    (None, "http:@www.example.com"),
    (None, "http:/@www.example.com"),
    (None, "http://@www.example.com"),
    (None, "http:a:b@www.example.com"),
    (None, "http:/a:b@www.example.com"),
    (None, "http://@pple.com"),
    (None, "http::b@www.example.com"),
    (None, "http:/:b@www.example.com"),
    (None, "http:/:@/www.example.com"),
    (None, "http://user@/www.example.com"),
    (None, "http:@/www.example.com"),
    (None, "http:/@/www.example.com"),
    (None, "http://@/www.example.com"),
    (None, "https:@/www.example.com"),
    (None, "http:a:b@/www.example.com"),
    (None, "http:/a:b@/www.example.com"),
    (None, "http://a:b@/www.example.com"),
    (None, "http::@/www.example.com"),
    (None, "http:a:@www.example.com"),
    (None, "http:/a:@www.example.com"),
    (None, "http://a:@www.example.com"),
    (None, "http:@:www.example.com"),
    (None, "http:/@:www.example.com"),
    (None, "http://:@www.example.com"),
    (None, "file:."),
    (None, "https://�"),
    (None, "https://%EF%BF%BD"),
    (None, "https://faß.ExAmPlE/"),
    (None, "https://x x:12"),
    (None, "http://a\x00b/"),
    (None, "http://a\x01b/"),
    (None, "http://a\x02b/"),
    (None, "http://a\x03b/"),
    (None, "http://a\x04b/"),
    (None, "http://a\x05b/"),
    (None, "http://a\x06b/"),
    (None, "http://a\x07b/"),
    (None, "http://a\x08b/"),
    (None, "http://a\x0bb/"),
    (None, "http://a\x0cb/"),
    (None, "http://a\x0eb/"),
    (None, "http://a\x0fb/"),
    (None, "http://a\x10b/"),
    (None, "http://a\x11b/"),
    (None, "http://a\x12b/"),
    (None, "http://a\x13b/"),
    (None, "http://a\x14b/"),
    (None, "http://a\x15b/"),
    (None, "http://a\x16b/"),
    (None, "http://a\x17b/"),
    (None, "http://a\x18b/"),
    (None, "http://a\x19b/"),
    (None, "http://a\x1ab/"),
    (None, "http://a\x1bb/"),
    (None, "http://a\x1cb/"),
    (None, "http://a\x1db/"),
    (None, "http://a\x1eb/"),
    (None, "http://a\x1fb/"),
    (None, "http://a b/"),
    (None, "http://a%b/"),
    (None, "http://a<b"),
    (None, "http://a>b"),
    (None, "http://a^b"),
    (None, "http://a|b/"),
    (None, "http://a\x7fb/"),
    (None, "http://ho%00st/"),
    (None, "http://ho%01st/"),
    (None, "http://ho%02st/"),
    (None, "http://ho%03st/"),
    (None, "http://ho%04st/"),
    (None, "http://ho%05st/"),
    (None, "http://ho%06st/"),
    (None, "http://ho%07st/"),
    (None, "http://ho%08st/"),
    (None, "http://ho%09st/"),
    (None, "http://ho%0Ast/"),
    (None, "http://ho%0Bst/"),
    (None, "http://ho%0Cst/"),
    (None, "http://ho%0Dst/"),
    (None, "http://ho%0Est/"),
    (None, "http://ho%0Fst/"),
    (None, "http://ho%10st/"),
    (None, "http://ho%11st/"),
    (None, "http://ho%12st/"),
    (None, "http://ho%13st/"),
    (None, "http://ho%14st/"),
    (None, "http://ho%15st/"),
    (None, "http://ho%16st/"),
    (None, "http://ho%17st/"),
    (None, "http://ho%18st/"),
    (None, "http://ho%19st/"),
    (None, "http://ho%1Ast/"),
    (None, "http://ho%1Bst/"),
    (None, "http://ho%1Cst/"),
    (None, "http://ho%1Dst/"),
    (None, "http://ho%1Est/"),
    (None, "http://ho%1Fst/"),
    (None, "http://ho%20st/"),
    (None, "http://ho%23st/"),
    (None, "http://ho%25st/"),
    (None, "http://ho%2Fst/"),
    (None, "http://ho%3Ast/"),
    (None, "http://ho%3Cst/"),
    (None, "http://ho%3Est/"),
    (None, "http://ho%3Fst/"),
    (None, "http://ho%40st/"),
    (None, "http://ho%5Bst/"),
    (None, "http://ho%5Cst/"),
    (None, "http://ho%5Dst/"),
    (None, "http://ho%7Cst/"),
    (None, "http://ho%7Fst/"),
    (None, "ftp://example.com%80/"),
    (None, "ftp://example.com%A0/"),
    (None, "https://example.com%80/"),
    (None, "https://example.com%A0/"),
    (None, "ftp://%e2%98%83"),
    (None, "https://%e2%98%83"),
    (None, "https://0x.0x.0"),
    (None, "https://0x.0x.0x.0x"),
    (None, "https://00.00.00.00"),
    (None, "https://0000000000000000000000000000000000000000177.0.0.1"),
    (None, "https://0x100000000/test"),
    (None, "https://256.0.0.1/test"),
    (None, "file://%43%3A"),
    (None, "file://%43%7C"),
    (None, "file://%43|"),
    (None, "file://C%7C"),
    (None, "file://%43%7C/"),
    (None, "https://%43%7C/"),
    (None, "file:\\\\localhost//"),
    (None, "file://localhost//a//../..//"),
    (None, "file:/C|/"),
    (None, "file://C|/"),
    (None, "\\\\\\.\\Y:"),
    (None, "\\\\\\.\\y:"),
    (None, "file://localhost//a//../..//foo"),
    (None, "file://localhost////foo"),
    (None, "file:.//p"),
    (None, "http://?"),
    (None, "http://#"),
    (None, "non-special://[1:2:0:0:5:0:0:0]/"),
    (None, "non-special://[1:2:0:0:0:0:0:3]/"),
    (None, "a"),
    (None, "a/"),
    (None, "a//"),
    (None, "file://a%C2%ADb/p"),
    (None, "file://loC𝐀𝐋𝐇𝐨𝐬𝐭/usr/bin"),
    (None, "file://\xad/p"),
    (None, "file://%C2%AD/p"),
    (None, "foo:// !\"$%&'()*+,-.;<=>@[\\]^_`{|}~@host/"),
    (None, "wss:// !\"$%&'()*+,-.;<=>@[]^_`{|}~@host/"),
    (None, "foo://joe: !\"$%&'()*+,-.:;<=>@[\\]^_`{|}~@host/"),
    (None, "wss://joe: !\"$%&'()*+,-.:;<=>@[]^_`{|}~@host/"),
    (None, "#"),
    (None, "?"),
    (None, "http://0..0x300/"),
    (None, "http://0..0x300./"),
    (None, "http://1.2.3.08"),
    (None, "http://1.2.3.08."),
    (None, "http://1.2.3.09"),
    (None, "http://09.2.3.4"),
    (None, "http://09.2.3.4."),
    (None, "http://01.2.3.4.5"),
    (None, "http://01.2.3.4.5."),
    (None, "http://0x100.2.3.4"),
    (None, "http://0x100.2.3.4."),
    (None, "http://0x1.2.3.4.5"),
    (None, "http://0x1.2.3.4.5."),
    (None, "http://foo.1.2.3.4"),
    (None, "http://foo.1.2.3.4."),
    (None, "http://foo.2.3.4"),
    (None, "http://foo.2.3.4."),
    (None, "http://foo.09"),
    (None, "http://foo.09."),
    (None, "http://foo.0x4"),
    (None, "http://foo.0x4."),
    (None, "http://0999999999999999999/"),
    (None, "http://foo.0x"),
    (None, "http://foo.0XFfFfFfFfFfFfFfFfFfAcE123"),
    (None, "http://💩.123/"),
    (None, "https://\x00y"),
    (None, "https://\uffffy"),
    (None, ""),
    (None, "https://a%C2%ADb/"),
    (None, "https://\xad/"),
    (None, "https://%C2%AD/"),
    ("http://example.org/foo/bar", "http://f:00000000000000000000080/c"),
    ("http://example.org/foo/bar", "http://&a:foo(b]c@d:2/"),
    ("http://example.org/foo/bar", "http://[::127.0.0.1]"),
    ("http://example.org/foo/bar", "http://[0:0:0:0:0:0:13.1.68.3]"),
    ("http://example.org/foo/bar", "http://[2001::1]:80"),
    ("http://example.org/foo/bar", "ftp:/example.com/"),
    ("http://example.org/foo/bar", "https:/example.com/"),
    ("http://example.org/foo/bar", "ws:/example.com/"),
    ("http://example.org/foo/bar", "wss:/example.com/"),
    ("http://example.org/foo/bar", "ftp:example.com/"),
    ("http://example.org/foo/bar", "https:example.com/"),
    ("http://example.org/foo/bar", "ws:example.com/"),
    ("http://example.org/foo/bar", "wss:example.com/"),
    ("file:///tmp/mock/path", "file:c:\\foo\\bar.html"),
    ("file:///tmp/mock/path", "  File:c|////foo\\bar.html"),
    ("file:///tmp/mock/path", "C|/foo/bar"),
    ("file:///tmp/mock/path", "/C|\\foo\\bar"),
    ("file:///tmp/mock/path", "//C|/foo/bar"),
    ("file:///tmp/mock/path", "file://localhost"),
    ("file:///tmp/mock/path", "file://localhost/"),
    ("file:///tmp/mock/path", "file://localhost/test"),
    ("http://www.example.com/test", "file:..."),
    ("http://www.example.com/test", "file:.."),
    ("http://www.example.com/test", "file:a"),
    ("http://www.example.com/test", "file:."),
    ("http://other.com/", "http://example example.com"),
    ("http://other.com/", "http://Goo%20 goo%7C|.com"),
    ("http://other.com/", "http://GOO\xa0\u3000goo.com"),
    ("http://other.com/", "http://\ufdd0zyx.com"),
    ("http://other.com/", "http://%ef%b7%90zyx.com"),
    ("http://other.com/", "http://％４１.com"),
    ("http://other.com/", "http://%ef%bc%85%ef%bc%94%ef%bc%91.com"),
    ("http://other.com/", "http://％００.com"),
    ("http://other.com/", "http://%ef%bc%85%ef%bc%90%ef%bc%90.com"),
    ("http://other.com/", "http://%zz%66%a.com"),
    ("http://other.com/", "http://%25"),
    ("http://other.com/", "http://hello%00"),
    ("http://other.com/", "http://%30%78%63%30%2e%30%32%35%30.01"),
    ("http://other.com/", "http://%30%78%63%30%2e%30%32%35%30.01%2e"),
    ("http://other.com/", "http://192.168.0.257"),
    ("http://other.com/", "http://%3g%78%63%30%2e%30%32%35%30%2E.01"),
    ("http://other.com/", "http://192.168.0.1 hello"),
    ("http://other.com/", "http://０Ｘｃ０．０２５０．０１"),
    ("http://other.com/", "http://[::%31]"),
    ("https://example.org/foo/bar", "http:"),
    ("http://other.com/", "http://1.2.3.4./"),
    ("http://other.com/", "http://192.168.257"),
    ("http://other.com/", "http://192.168.257."),
    ("http://other.com/", "http://256"),
    ("http://other.com/", "http://999999999"),
    ("http://other.com/", "http://999999999."),
    ("http://other.com/", "http://10000000000"),
    ("http://other.com/", "http://4294967295"),
    ("http://other.com/", "http://4294967296"),
    ("http://other.com/", "http://18446744073709551616"),
    ("http://other.com/", "http://18446744075840258049"),
    ("http://other.com/", "http://0xffffffff"),
    ("http://other.com/", "http://0xffffffff1"),
    ("http://other.com/", "http://256.256.256.256"),
    ("file:///C:/", ".."),
    ("file:///C:/a/b", "/"),
    ("file://h/C:/a/b", "/"),
    ("file:///C:/a/b", "//d:"),
    ("file:///C:/a/b", "//d:/.."),
    ("file://lion/", "\\/localhost//pig"),
    ("file://lion/", "//localhost//pig"),
    ("file://host/dir/file", "C|"),
    ("file://host/D:/dir1/dir2/file", "C|"),
    ("file://host/dir/file", "C|#"),
    ("file://host/dir/file", "C|?"),
    ("file://host/dir/file", "C|/"),
    ("file://host/dir/file", "C|\n/"),
    ("file://host/dir/file", "C|\\"),
    ("file:///c:/baz/qux", "/c|/foo/bar"),
    ("file://x/C:/", ".."),
    ("file://host/", "C|/"),
    ("file://host/", "//C:/"),
    ("file://host/", "file://C:/"),
    ("http://example.net/", "http://[1:0::]"),
    ("http://example.org", "https://user:pass[\x7f@foo/bar"),
    ("http://other.com/", "http://1.2.3.4.5"),
    ("http://other.com/", "http://1.2.3.4.5."),
    ("http://other.com/", "http://256.256.256.256.256"),
    ("http://other.com/", "http://256.256.256.256.256."),
}


_DIVERGENCES: dict[tuple[str | None, str], str] = {}


def _params() -> list[Any]:
    path = Path(__file__).parent / "wpt" / "urltestdata.json"
    params = []
    for case in json.loads(path.read_text(encoding="utf-8")):
        if isinstance(case, str):
            continue
        key = (case["base"], case["input"])
        marks = []
        if key in _KNOWN_FAILURES:
            marks.append(pytest.mark.xfail(strict=True))
        elif key in _DIVERGENCES:
            marks.append(pytest.mark.xfail(strict=True, reason=_DIVERGENCES[key]))
        params.append(pytest.param(case, id=repr(key), marks=marks))
    return params


@pytest.mark.parametrize("case", _params())
def test_urltestdata(case: dict[str, Any]) -> None:
    def parse() -> str:
        if case["base"] is None:
            return safe_url_string(case["input"])
        return safe_url_string(_urljoin(case["base"], case["input"]))

    if case.get("failure"):
        with pytest.raises(ValueError):  # noqa: PT011
            parse()
    else:
        assert parse() == safe_url_string(case["href"])
