from ._infra import _ASCII_ALPHANUMERIC
from ._util import _PercentEncodeSet


_RFC2396_MARK_PERCENT_ENCODE_SET = _PercentEncodeSet("-_.!~*'()", exclude=True)
_RFC2396_UNRESERVED_PERCENT_ENCODE_SET = (
    _RFC2396_MARK_PERCENT_ENCODE_SET - _ASCII_ALPHANUMERIC
)
_RFC2396_USERINFO_PERCENT_ENCODE_SET = (
    _RFC2396_UNRESERVED_PERCENT_ENCODE_SET - ";:&=+$,"
)
