from ._infra import _ASCII_ALPHANUMERIC
from ._util import _PercentEncodeSet


_RFC2396_MARK_PERCENT_ENCODE_SET = _PercentEncodeSet("-_.!~*'()", exclude=True)
_RFC2396_RESERVED_PERCENT_ENCODE_SET = _PercentEncodeSet(";/?:@&=+$,", exclude=True)
_RFC2396_UNRESERVED_PERCENT_ENCODE_SET = (
    _RFC2396_MARK_PERCENT_ENCODE_SET - _ASCII_ALPHANUMERIC
)
_RFC2396_USERINFO_PERCENT_ENCODE_SET = (
    _RFC2396_UNRESERVED_PERCENT_ENCODE_SET - ";:&=+$,"
)
_RFC2396_ABS_PATH_PERCENT_ENCODE_SET = (
    _RFC2396_UNRESERVED_PERCENT_ENCODE_SET
    - ":@&=+$,"  # pchar
    - "/"  # abs_path, path_segments
    - ";"  # segment
)
_RFC2396_QUERY_PERCENT_ENCODE_SET = (
    _RFC2396_RESERVED_PERCENT_ENCODE_SET
    & _RFC2396_UNRESERVED_PERCENT_ENCODE_SET
)
_RFC2396_FRAGMENT_PERCENT_ENCODE_SET = _RFC2396_QUERY_PERCENT_ENCODE_SET
