---
name: codspeed

on:
    push:
        branches:
            - master
    pull_request:
        paths:
            - w3lib/**
            - tests/benchmarks/**
            - .github/workflows/codspeed.yml
            - pyproject.toml
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    benchmark:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.13', pypy3.11]
                submodule-to-bench: [encoding, html, http, url]

        steps:
            - uses: actions/checkout@v6

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v6
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install deps
              run: |
                  pip install --upgrade pip
                  pip install --upgrade tox
                  tox -n -e benchmark-${{ matrix.python-version }}
            - name: Run benchmarks on ${{ matrix.python-version }}
              uses: CodSpeedHQ/action@v4
              with:
                  mode: simulation
                  run: tox --skip-env-install --skip-pkg-install -e benchmark-${{ matrix.python-version }} -- ${{ matrix.submodule-to-bench }}
